# ═══════════════════════════════════════════════════════════════
# AUTO-GENERATED BY AUDIO CLASSIFICATION HUB (COMPANY CLASSIFICATION)
# This file contains voice embeddings for your team.
# ═══════════════════════════════════════════════════════════════

import numpy as np
from .preprocess import clean_audio
from .similarity import cosine_similarity, decide
from .exceptions import AudioFileNotFoundError

# Dictionary of { "PersonName": [192-dim array] }
COMPANY_EMBEDDINGS = {{COMPANY_EMBEDDINGS}}

# Convert back to numpy arrays
for k in COMPANY_EMBEDDINGS:
    COMPANY_EMBEDDINGS[k] = np.array(COMPANY_EMBEDDINGS[k], dtype=np.float32)


def identify(audio_path: str, threshold: float = 0.65) -> str:
    """
    Identify who is speaking from the company team.
    
    Returns:
        "PersonName" if a match is found above threshold.
        "Unknown" if no match is found.
    """
    person, score = identify_with_score(audio_path)
    if score >= threshold:
        return person
    return "Unknown"


def identify_with_score(audio_path: str) -> tuple:
    """
    Returns: (PersonName, max_score)
    """
    audio  = clean_audio(audio_path)

    # Inline embedding computation
    import torch
    try:
        from speechbrain.inference.classifiers import EncoderClassifier
    except ImportError:
        from speechbrain.pretrained import EncoderClassifier

    _model_dir = "pretrained_models/spkrec-ecapa-voxceleb"

    # Lazy singleton
    import importlib
    pkg = importlib.import_module(__package__)
    if not hasattr(pkg, "_ecapa_model"):
        pkg._ecapa_model = EncoderClassifier.from_hparams(
            source="speechbrain/spkrec-ecapa-voxceleb",
            savedir=_model_dir,
            run_opts={"device": "cpu"},
        )

    tensor = torch.FloatTensor(audio).unsqueeze(0)
    with torch.no_grad():
        emb = pkg._ecapa_model.encode_batch(tensor)
    new_emb = emb.squeeze().numpy().astype(np.float32)

    best_match = "Unknown"
    best_score = -1.0

    for name, master_emb in COMPANY_EMBEDDINGS.items():
        score = cosine_similarity(master_emb, new_emb)
        if score > best_score:
            best_score = score
            best_match = name

    return best_match, float(best_score)
