# ═══════════════════════════════════════════════════════════════
# AUTO-GENERATED BY AUDIO CLASSIFICATION HUB
# This file contains YOUR voice embedding baked in.
# Do not edit manually.
# ═══════════════════════════════════════════════════════════════

import numpy as np
from .preprocess import clean_audio
from .similarity import cosine_similarity, decide
from .exceptions import AudioFileNotFoundError

# Your 192-dimensional voice fingerprint — injected at build time
MASTER_EMBEDDING = np.array({{EMBEDDING}}, dtype=np.float32)


def authenticate(audio_path: str) -> bool:
    """
    Authenticate a voice against the enrolled voice fingerprint.

    Usage:
        from audioauth import authenticate
        result = authenticate("test.wav")
        print(result)  # True or False

    Args:
        audio_path: path to .wav / .mp3 / .flac file

    Returns:
        True  — voice matches (authenticated)
        False — voice does not match (rejected)
    """
    _, result = authenticate_with_score(audio_path)
    return result


def authenticate_with_score(audio_path: str) -> tuple:
    """
    Same as authenticate() but also returns the similarity score.

    Returns:
        (score: float, authenticated: bool)
        score is between 0.0 and 1.0
        1.0 = identical voice, 0.0 = completely different
    """
    audio  = clean_audio(audio_path)

    # Inline embedding computation to avoid circular import
    import torch
    try:
        from speechbrain.inference.classifiers import EncoderClassifier
    except ImportError:
        from speechbrain.pretrained import EncoderClassifier

    _model_dir = "pretrained_models/spkrec-ecapa-voxceleb"

    # Lazy singleton inside the package
    import importlib
    pkg = importlib.import_module(__package__)
    if not hasattr(pkg, "_ecapa_model"):
        pkg._ecapa_model = EncoderClassifier.from_hparams(
            source="speechbrain/spkrec-ecapa-voxceleb",
            savedir=_model_dir,
        )

    tensor = torch.FloatTensor(audio).unsqueeze(0)
    with torch.no_grad():
        emb = pkg._ecapa_model.encode_batch(tensor)
    new_emb = emb.squeeze().numpy().astype(np.float32)

    score = cosine_similarity(MASTER_EMBEDDING, new_emb)
    auth, _label = decide(score)

    return score, auth
